const MAIN_THEME_COLOR = '#01E096';
const SECONDARY_THEME_COLOR = '#F0F4F8';
const MAIN_TEXT_COLOR = '#A6BCD0';
const SECONDARY_TEXT_COLOR = '#748A9D';
const MAIN_BACKGROUND_COLOR = '#FFFFFF';
const DISABLED_COLOR = '#D8D8D8';
const MOTION_ANIMATION_COLOR = 'rgba(1, 224,150, 0.05)';
const FACEBOOK_BLUE_COLOR = '#4267B2';
const ERROR_COLOR = '#FF496B';

export {
  MAIN_THEME_COLOR,
  SECONDARY_THEME_COLOR,
  MAIN_TEXT_COLOR,
  SECONDARY_TEXT_COLOR,
  MAIN_BACKGROUND_COLOR,
  DISABLED_COLOR,
  MOTION_ANIMATION_COLOR,
  FACEBOOK_BLUE_COLOR,
  ERROR_COLOR
};
