const VALIDATOR_TEXT_SIZE = 12;
const NORMAL_TEXT_SIZE = 16;
const HEADER_TEXT_SIZE = 22;

const NORMAL_TEXT_FONT_FAMILY = 'lato-regular';
const BOLD_TEXT_FONT_FAMILY = 'lato-bold';

export {
  VALIDATOR_TEXT_SIZE,
  NORMAL_TEXT_SIZE,
  HEADER_TEXT_SIZE,
  NORMAL_TEXT_FONT_FAMILY,
  BOLD_TEXT_FONT_FAMILY
};
